"""platform schema

Revision ID: 0002_platform
Revises: 0001_auth
Create Date: 2026-09-02 20:02:48.222521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0002_platform'
down_revision: Union[str, Sequence[str], None] = '0001_auth'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_rules',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('scope_ref', sa.String(length=64), nullable=True),
    sa.Column('rule_type', sa.String(length=24), nullable=False),
    sa.Column('params', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("rule_type IN ('max_positions','one_per_symbol','max_daily_loss','max_exposure_currency','max_risk_per_trade','kill_switch','mode_gate')", name=op.f('ck_risk_rules_rule_type')),
    sa.CheckConstraint("scope IN ('global','broker_account','paper_account','strategy','symbol')", name=op.f('ck_risk_rules_scope')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_rules'))
    )
    op.create_table('roles',
    sa.Column('name', sa.String(length=16), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('name', name=op.f('pk_roles'))
    )
    op.create_table('symbols',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('asset_class', sa.String(length=16), nullable=False),
    sa.Column('base_currency', sa.String(length=8), nullable=True),
    sa.Column('quote_currency', sa.String(length=8), nullable=True),
    sa.Column('digits', sa.Integer(), nullable=True),
    sa.Column('point_size', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('unit_class', sa.String(length=8), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("asset_class IN ('fx','index','metal','crypto','equity','other')", name=op.f('ck_symbols_asset_class')),
    sa.CheckConstraint("unit_class IN ('points','percent')", name=op.f('ck_symbols_unit_class')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_symbols'))
    )
    op.create_index(op.f('ix_symbols_code'), 'symbols', ['code'], unique=True)
    op.create_table('system_events',
    sa.Column('component', sa.String(length=32), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('level', sa.String(length=8), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.CheckConstraint("level IN ('debug','info','warning','error','critical')", name=op.f('ck_system_events_level')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_events'))
    )
    op.create_index(op.f('ix_system_events_component'), 'system_events', ['component'], unique=False)
    op.create_index(op.f('ix_system_events_correlation_id'), 'system_events', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_system_events_event_type'), 'system_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_system_events_occurred_at'), 'system_events', ['occurred_at'], unique=False)
    op.create_table('webhook_events',
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('source_ip', sa.String(length=64), nullable=True),
    sa.Column('auth_strength', sa.String(length=8), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('signal_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.CheckConstraint("auth_strength IN ('strong','weak','none')", name=op.f('ck_webhook_events_auth_strength')),
    sa.CheckConstraint("status IN ('accepted','rejected','duplicate')", name=op.f('ck_webhook_events_status')),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], name='fk_webhook_signal', ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhook_events'))
    )
    op.create_index(op.f('ix_webhook_events_idempotency_key'), 'webhook_events', ['idempotency_key'], unique=True)
    op.create_table('symbol_mappings',
    sa.Column('symbol_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('provider_symbol', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("provider IN ('mt5','tradingview','ccxt','yfinance','simulator')", name=op.f('ck_symbol_mappings_provider')),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], name=op.f('fk_symbol_mappings_symbol_id_symbols'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_symbol_mappings')),
    sa.UniqueConstraint('provider', 'provider_symbol', name='provider_symbol'),
    sa.UniqueConstraint('symbol_id', 'provider', name='symbol_provider')
    )
    op.create_index(op.f('ix_symbol_mappings_symbol_id'), 'symbol_mappings', ['symbol_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('actor_user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_logs_actor_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_occurred_at'), 'audit_logs', ['occurred_at'], unique=False)
    op.create_table('broker_accounts',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('broker', sa.String(length=16), nullable=False),
    sa.Column('account_mode', sa.String(length=8), nullable=False),
    sa.Column('login', sa.String(length=64), nullable=True),
    sa.Column('server', sa.String(length=128), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("account_mode IN ('demo','live')", name=op.f('ck_broker_accounts_account_mode')),
    sa.CheckConstraint("broker IN ('mt5','fake')", name=op.f('ck_broker_accounts_broker')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_broker_accounts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_broker_accounts'))
    )
    op.create_index(op.f('ix_broker_accounts_user_id'), 'broker_accounts', ['user_id'], unique=False)
    op.create_table('models',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_user_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("kind IN ('identity','classifier','regressor','llm_agent','other')", name=op.f('ck_models_kind')),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_models_owner_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_models'))
    )
    op.create_index(op.f('ix_models_key'), 'models', ['key'], unique=True)
    op.create_table('notifications',
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('channel', sa.String(length=8), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=8), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("channel IN ('inapp','email','push','discord')", name=op.f('ck_notifications_channel')),
    sa.CheckConstraint("severity IN ('info','warning','critical')", name=op.f('ck_notifications_severity')),
    sa.CheckConstraint("status IN ('pending','sent','failed','read')", name=op.f('ck_notifications_status')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_status'), 'notifications', ['status'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('paper_accounts',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('starting_balance', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('balance', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('equity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_paper_accounts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_paper_accounts'))
    )
    op.create_index(op.f('ix_paper_accounts_user_id'), 'paper_accounts', ['user_id'], unique=False)
    op.create_table('strategies',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('tier', sa.String(length=16), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_user_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("tier IN ('research_only','live_demo')", name=op.f('ck_strategies_tier')),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_strategies_owner_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_strategies'))
    )
    op.create_index(op.f('ix_strategies_key'), 'strategies', ['key'], unique=True)
    op.create_table('model_versions',
    sa.Column('model_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('artifact_ref', sa.String(length=260), nullable=True),
    sa.Column('features', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('labels', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('validation_report_ref', sa.String(length=260), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('draft','validated','promoted','retired')", name=op.f('ck_model_versions_status')),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], name=op.f('fk_model_versions_model_id_models'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_versions')),
    sa.UniqueConstraint('model_id', 'version', name='model_version')
    )
    op.create_index(op.f('ix_model_versions_model_id'), 'model_versions', ['model_id'], unique=False)
    op.create_table('mt5_connections',
    sa.Column('broker_account_id', sa.String(length=36), nullable=False),
    sa.Column('terminal_path', sa.String(length=260), nullable=True),
    sa.Column('host', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('trade_allowed', sa.Boolean(), nullable=True),
    sa.Column('build', sa.Integer(), nullable=True),
    sa.Column('last_heartbeat_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('disconnected','connecting','connected','reconciling','error')", name=op.f('ck_mt5_connections_status')),
    sa.ForeignKeyConstraint(['broker_account_id'], ['broker_accounts.id'], name=op.f('fk_mt5_connections_broker_account_id_broker_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mt5_connections'))
    )
    op.create_index(op.f('ix_mt5_connections_broker_account_id'), 'mt5_connections', ['broker_account_id'], unique=False)
    op.create_table('portfolio_snapshots',
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('broker_account_id', sa.String(length=36), nullable=True),
    sa.Column('paper_account_id', sa.String(length=36), nullable=True),
    sa.Column('mode', sa.String(length=8), nullable=False),
    sa.Column('taken_at', sa.DateTime(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('equity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('margin', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('free_margin', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('open_positions', sa.Integer(), nullable=False),
    sa.Column('exposure', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('drawdown_pct', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.CheckConstraint("mode IN ('paper','demo','live')", name=op.f('ck_portfolio_snapshots_mode')),
    sa.ForeignKeyConstraint(['broker_account_id'], ['broker_accounts.id'], name=op.f('fk_portfolio_snapshots_broker_account_id_broker_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paper_account_id'], ['paper_accounts.id'], name=op.f('fk_portfolio_snapshots_paper_account_id_paper_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_portfolio_snapshots_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portfolio_snapshots'))
    )
    op.create_index(op.f('ix_portfolio_snapshots_broker_account_id'), 'portfolio_snapshots', ['broker_account_id'], unique=False)
    op.create_index(op.f('ix_portfolio_snapshots_paper_account_id'), 'portfolio_snapshots', ['paper_account_id'], unique=False)
    op.create_index(op.f('ix_portfolio_snapshots_taken_at'), 'portfolio_snapshots', ['taken_at'], unique=False)
    op.create_table('strategy_versions',
    sa.Column('strategy_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('code_ref', sa.String(length=200), nullable=False),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('validation_report_ref', sa.String(length=260), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('draft','validated','retired')", name=op.f('ck_strategy_versions_status')),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], name=op.f('fk_strategy_versions_strategy_id_strategies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_strategy_versions')),
    sa.UniqueConstraint('strategy_id', 'version', name='strategy_version')
    )
    op.create_index(op.f('ix_strategy_versions_strategy_id'), 'strategy_versions', ['strategy_id'], unique=False)
    op.create_table('backtests',
    sa.Column('strategy_version_id', sa.String(length=36), nullable=True),
    sa.Column('requested_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('engine', sa.String(length=16), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=True),
    sa.Column('universe', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('params', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('summary', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('report_path', sa.String(length=260), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("engine IN ('rule_backtest','rule_search','exit_search','bracket_sweep','score_backtest','patterns','replay')", name=op.f('ck_backtests_engine')),
    sa.CheckConstraint("status IN ('queued','running','finished','failed','cancelled')", name=op.f('ck_backtests_status')),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], name=op.f('fk_backtests_requested_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['strategy_version_id'], ['strategy_versions.id'], name=op.f('fk_backtests_strategy_version_id_strategy_versions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_backtests'))
    )
    op.create_table('bots',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('mode', sa.String(length=8), nullable=False),
    sa.Column('strategy_version_id', sa.String(length=36), nullable=True),
    sa.Column('broker_account_id', sa.String(length=36), nullable=True),
    sa.Column('paper_account_id', sa.String(length=36), nullable=True),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("mode IN ('paper','demo','live')", name=op.f('ck_bots_mode')),
    sa.ForeignKeyConstraint(['broker_account_id'], ['broker_accounts.id'], name=op.f('fk_bots_broker_account_id_broker_accounts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['paper_account_id'], ['paper_accounts.id'], name=op.f('fk_bots_paper_account_id_paper_accounts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['strategy_version_id'], ['strategy_versions.id'], name=op.f('fk_bots_strategy_version_id_strategy_versions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_bots_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bots'))
    )
    op.create_index(op.f('ix_bots_user_id'), 'bots', ['user_id'], unique=False)
    op.create_table('positions',
    sa.Column('mode', sa.String(length=8), nullable=False),
    sa.Column('broker_account_id', sa.String(length=36), nullable=True),
    sa.Column('paper_account_id', sa.String(length=36), nullable=True),
    sa.Column('symbol_id', sa.String(length=36), nullable=False),
    sa.Column('strategy_version_id', sa.String(length=36), nullable=True),
    sa.Column('broker_position_id', sa.String(length=64), nullable=True),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('stop_loss', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('take_profit', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("mode IN ('paper','demo','live')", name=op.f('ck_positions_mode')),
    sa.CheckConstraint("side IN ('long','short')", name=op.f('ck_positions_side')),
    sa.CheckConstraint("source IN ('pipeline','jsonl_import','manual','simulator')", name=op.f('ck_positions_source')),
    sa.CheckConstraint("status IN ('open','closed','unknown')", name=op.f('ck_positions_status')),
    sa.ForeignKeyConstraint(['broker_account_id'], ['broker_accounts.id'], name=op.f('fk_positions_broker_account_id_broker_accounts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['paper_account_id'], ['paper_accounts.id'], name=op.f('fk_positions_paper_account_id_paper_accounts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['strategy_version_id'], ['strategy_versions.id'], name=op.f('fk_positions_strategy_version_id_strategy_versions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], name=op.f('fk_positions_symbol_id_symbols')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_positions'))
    )
    op.create_index(op.f('ix_positions_broker_position_id'), 'positions', ['broker_position_id'], unique=False)
    op.create_index(op.f('ix_positions_status'), 'positions', ['status'], unique=False)
    op.create_index(op.f('ix_positions_symbol_id'), 'positions', ['symbol_id'], unique=False)
    op.create_table('replay_sessions',
    sa.Column('strategy_version_id', sa.String(length=36), nullable=True),
    sa.Column('paper_account_id', sa.String(length=36), nullable=True),
    sa.Column('requested_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('universe', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('from_time', sa.DateTime(), nullable=False),
    sa.Column('to_time', sa.DateTime(), nullable=False),
    sa.Column('speed', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('cursor_time', sa.DateTime(), nullable=True),
    sa.Column('summary', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('queued','running','finished','failed','cancelled')", name=op.f('ck_replay_sessions_status')),
    sa.ForeignKeyConstraint(['paper_account_id'], ['paper_accounts.id'], name=op.f('fk_replay_sessions_paper_account_id_paper_accounts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], name=op.f('fk_replay_sessions_requested_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['strategy_version_id'], ['strategy_versions.id'], name=op.f('fk_replay_sessions_strategy_version_id_strategy_versions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_replay_sessions'))
    )
    op.create_table('signals',
    sa.Column('signal_key', sa.String(length=128), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('strategy_version_id', sa.String(length=36), nullable=True),
    sa.Column('webhook_event_id', sa.String(length=36), nullable=True),
    sa.Column('symbol_id', sa.String(length=36), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('mode', sa.String(length=8), nullable=False),
    sa.Column('signal_time', sa.DateTime(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('auth_strength', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('ai_model_version_id', sa.String(length=36), nullable=True),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.CheckConstraint("auth_strength IN ('strong','weak','internal')", name=op.f('ck_signals_auth_strength')),
    sa.CheckConstraint("direction IN ('buy','sell','flat')", name=op.f('ck_signals_direction')),
    sa.CheckConstraint("mode IN ('paper','demo','live')", name=op.f('ck_signals_mode')),
    sa.CheckConstraint("source IN ('strategy','tradingview','manual')", name=op.f('ck_signals_source')),
    sa.CheckConstraint("status IN ('new','approved','vetoed','expired','executed')", name=op.f('ck_signals_status')),
    sa.ForeignKeyConstraint(['ai_model_version_id'], ['model_versions.id'], name=op.f('fk_signals_ai_model_version_id_model_versions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['strategy_version_id'], ['strategy_versions.id'], name=op.f('fk_signals_strategy_version_id_strategy_versions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], name=op.f('fk_signals_symbol_id_symbols')),
    sa.ForeignKeyConstraint(['webhook_event_id'], ['webhook_events.id'], name=op.f('fk_signals_webhook_event_id_webhook_events'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signals'))
    )
    op.create_index(op.f('ix_signals_signal_key'), 'signals', ['signal_key'], unique=True)
    op.create_index(op.f('ix_signals_signal_time'), 'signals', ['signal_time'], unique=False)
    op.create_index(op.f('ix_signals_symbol_id'), 'signals', ['symbol_id'], unique=False)
    op.create_table('strategy_parameters',
    sa.Column('strategy_version_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('value_type', sa.String(length=16), nullable=False),
    sa.Column('value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['strategy_version_id'], ['strategy_versions.id'], name=op.f('fk_strategy_parameters_strategy_version_id_strategy_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_strategy_parameters')),
    sa.UniqueConstraint('strategy_version_id', 'name', name='version_param')
    )
    op.create_index(op.f('ix_strategy_parameters_strategy_version_id'), 'strategy_parameters', ['strategy_version_id'], unique=False)
    op.create_table('training_runs',
    sa.Column('model_version_id', sa.String(length=36), nullable=False),
    sa.Column('dataset_ref', sa.String(length=260), nullable=True),
    sa.Column('params', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('log_ref', sa.String(length=260), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.CheckConstraint("status IN ('queued','running','finished','failed','cancelled')", name=op.f('ck_training_runs_status')),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], name=op.f('fk_training_runs_model_version_id_model_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_training_runs'))
    )
    op.create_index(op.f('ix_training_runs_model_version_id'), 'training_runs', ['model_version_id'], unique=False)
    op.create_table('backtest_trades',
    sa.Column('backtest_id', sa.String(length=36), nullable=False),
    sa.Column('symbol_id', sa.String(length=36), nullable=True),
    sa.Column('candidate', sa.String(length=64), nullable=True),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('entry_time', sa.DateTime(), nullable=False),
    sa.Column('exit_time', sa.DateTime(), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('exit_price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('pnl_points', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('pnl_pct', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('r_multiple', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('exit_reason', sa.String(length=24), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.CheckConstraint("side IN ('long','short')", name=op.f('ck_backtest_trades_side')),
    sa.ForeignKeyConstraint(['backtest_id'], ['backtests.id'], name=op.f('fk_backtest_trades_backtest_id_backtests'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], name=op.f('fk_backtest_trades_symbol_id_symbols'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_backtest_trades'))
    )
    op.create_index(op.f('ix_backtest_trades_backtest_id'), 'backtest_trades', ['backtest_id'], unique=False)
    op.create_index(op.f('ix_backtest_trades_entry_time'), 'backtest_trades', ['entry_time'], unique=False)
    op.create_table('bot_runs',
    sa.Column('bot_id', sa.String(length=36), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('host', sa.String(length=128), nullable=True),
    sa.Column('last_heartbeat_at', sa.DateTime(), nullable=True),
    sa.Column('stop_reason', sa.Text(), nullable=True),
    sa.Column('summary', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.CheckConstraint("status IN ('starting','running','stopping','stopped','crashed','halted')", name=op.f('ck_bot_runs_status')),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], name=op.f('fk_bot_runs_bot_id_bots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bot_runs'))
    )
    op.create_index(op.f('ix_bot_runs_bot_id'), 'bot_runs', ['bot_id'], unique=False)
    op.create_index(op.f('ix_bot_runs_status'), 'bot_runs', ['status'], unique=False)
    op.create_table('model_predictions',
    sa.Column('model_version_id', sa.String(length=36), nullable=False),
    sa.Column('signal_id', sa.String(length=36), nullable=True),
    sa.Column('symbol_id', sa.String(length=36), nullable=True),
    sa.Column('predicted_at', sa.DateTime(), nullable=False),
    sa.Column('horizon', sa.String(length=16), nullable=True),
    sa.Column('prediction', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('realized', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('realized_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], name=op.f('fk_model_predictions_model_version_id_model_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], name=op.f('fk_model_predictions_signal_id_signals'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], name=op.f('fk_model_predictions_symbol_id_symbols'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_predictions'))
    )
    op.create_index(op.f('ix_model_predictions_model_version_id'), 'model_predictions', ['model_version_id'], unique=False)
    op.create_index(op.f('ix_model_predictions_predicted_at'), 'model_predictions', ['predicted_at'], unique=False)
    op.create_index(op.f('ix_model_predictions_signal_id'), 'model_predictions', ['signal_id'], unique=False)
    op.create_table('orders',
    sa.Column('intent_id', sa.String(length=128), nullable=False),
    sa.Column('mode', sa.String(length=8), nullable=False),
    sa.Column('broker_account_id', sa.String(length=36), nullable=True),
    sa.Column('paper_account_id', sa.String(length=36), nullable=True),
    sa.Column('symbol_id', sa.String(length=36), nullable=False),
    sa.Column('signal_id', sa.String(length=36), nullable=True),
    sa.Column('strategy_version_id', sa.String(length=36), nullable=True),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('order_type', sa.String(length=8), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('requested_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('stop_loss', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('take_profit', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('broker_order_id', sa.String(length=64), nullable=True),
    sa.Column('magic', sa.Integer(), nullable=True),
    sa.Column('sizing', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("mode IN ('paper','demo','live')", name=op.f('ck_orders_mode')),
    sa.CheckConstraint("order_type IN ('market','limit','stop')", name=op.f('ck_orders_order_type')),
    sa.CheckConstraint("side IN ('buy','sell')", name=op.f('ck_orders_side')),
    sa.CheckConstraint("source IN ('pipeline','jsonl_import','manual','simulator')", name=op.f('ck_orders_source')),
    sa.CheckConstraint("status IN ('intent','submitted','accepted','partially_filled','filled','rejected','cancelled','unknown')", name=op.f('ck_orders_status')),
    sa.ForeignKeyConstraint(['broker_account_id'], ['broker_accounts.id'], name=op.f('fk_orders_broker_account_id_broker_accounts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['paper_account_id'], ['paper_accounts.id'], name=op.f('fk_orders_paper_account_id_paper_accounts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], name=op.f('fk_orders_signal_id_signals'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['strategy_version_id'], ['strategy_versions.id'], name=op.f('fk_orders_strategy_version_id_strategy_versions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], name=op.f('fk_orders_symbol_id_symbols')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders'))
    )
    op.create_index(op.f('ix_orders_broker_order_id'), 'orders', ['broker_order_id'], unique=False)
    op.create_index(op.f('ix_orders_intent_id'), 'orders', ['intent_id'], unique=True)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_symbol_id'), 'orders', ['symbol_id'], unique=False)
    op.create_table('paper_positions',
    sa.Column('paper_account_id', sa.String(length=36), nullable=False),
    sa.Column('position_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('last_mark_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('floating_pnl', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('last_marked_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['paper_account_id'], ['paper_accounts.id'], name=op.f('fk_paper_positions_paper_account_id_paper_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], name=op.f('fk_paper_positions_position_id_positions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_paper_positions'))
    )
    op.create_index(op.f('ix_paper_positions_paper_account_id'), 'paper_positions', ['paper_account_id'], unique=False)
    op.create_index(op.f('ix_paper_positions_position_id'), 'paper_positions', ['position_id'], unique=True)
    op.create_table('position_events',
    sa.Column('position_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=24), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], name=op.f('fk_position_events_position_id_positions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_position_events'))
    )
    op.create_index(op.f('ix_position_events_occurred_at'), 'position_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_position_events_position_id'), 'position_events', ['position_id'], unique=False)
    op.create_table('trades',
    sa.Column('mode', sa.String(length=8), nullable=False),
    sa.Column('position_id', sa.String(length=36), nullable=True),
    sa.Column('broker_position_id', sa.String(length=64), nullable=True),
    sa.Column('symbol_id', sa.String(length=36), nullable=False),
    sa.Column('strategy_version_id', sa.String(length=36), nullable=True),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('volume', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('exit_price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=False),
    sa.Column('gross_profit', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('commission', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('swap', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('net_profit', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('r_multiple', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('bracket', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('close_reason', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('imported_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.CheckConstraint("mode IN ('paper','demo','live')", name=op.f('ck_trades_mode')),
    sa.CheckConstraint("side IN ('long','short')", name=op.f('ck_trades_side')),
    sa.CheckConstraint("source IN ('pipeline','jsonl_import','manual','simulator')", name=op.f('ck_trades_source')),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], name=op.f('fk_trades_position_id_positions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['strategy_version_id'], ['strategy_versions.id'], name=op.f('fk_trades_strategy_version_id_strategy_versions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], name=op.f('fk_trades_symbol_id_symbols')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trades'))
    )
    op.create_index(op.f('ix_trades_broker_position_id'), 'trades', ['broker_position_id'], unique=True)
    op.create_index(op.f('ix_trades_closed_at'), 'trades', ['closed_at'], unique=False)
    op.create_index(op.f('ix_trades_opened_at'), 'trades', ['opened_at'], unique=False)
    op.create_index(op.f('ix_trades_symbol_id'), 'trades', ['symbol_id'], unique=False)
    op.create_table('bot_events',
    sa.Column('bot_run_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('level', sa.String(length=8), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.CheckConstraint("level IN ('info','warning','error')", name=op.f('ck_bot_events_level')),
    sa.ForeignKeyConstraint(['bot_run_id'], ['bot_runs.id'], name=op.f('fk_bot_events_bot_run_id_bot_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bot_events'))
    )
    op.create_index(op.f('ix_bot_events_bot_run_id'), 'bot_events', ['bot_run_id'], unique=False)
    op.create_index(op.f('ix_bot_events_occurred_at'), 'bot_events', ['occurred_at'], unique=False)
    op.create_table('executions',
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('broker_deal_id', sa.String(length=64), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('commission', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('swap', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('slippage_points', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('fill_source', sa.String(length=16), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.CheckConstraint("fill_source IN ('broker','simulator','import')", name=op.f('ck_executions_fill_source')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_executions_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_executions'))
    )
    op.create_index(op.f('ix_executions_broker_deal_id'), 'executions', ['broker_deal_id'], unique=False)
    op.create_index(op.f('ix_executions_order_id'), 'executions', ['order_id'], unique=False)
    op.create_table('journal_entries',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('trade_id', sa.String(length=36), nullable=True),
    sa.Column('position_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('ai_review', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], name=op.f('fk_journal_entries_position_id_positions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], name=op.f('fk_journal_entries_trade_id_trades'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_journal_entries_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_journal_entries'))
    )
    op.create_index(op.f('ix_journal_entries_trade_id'), 'journal_entries', ['trade_id'], unique=False)
    op.create_index(op.f('ix_journal_entries_user_id'), 'journal_entries', ['user_id'], unique=False)
    op.create_table('order_events',
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=24), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('retcode', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_events_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_events'))
    )
    op.create_index(op.f('ix_order_events_occurred_at'), 'order_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_order_events_order_id'), 'order_events', ['order_id'], unique=False)
    op.create_table('paper_orders',
    sa.Column('paper_account_id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('replay_session_id', sa.String(length=36), nullable=True),
    sa.Column('simulated_fill_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('simulated_at', sa.DateTime(), nullable=True),
    sa.Column('spread_charged', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('bar_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_paper_orders_order_id_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paper_account_id'], ['paper_accounts.id'], name=op.f('fk_paper_orders_paper_account_id_paper_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['replay_session_id'], ['replay_sessions.id'], name=op.f('fk_paper_orders_replay_session_id_replay_sessions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_paper_orders'))
    )
    op.create_index(op.f('ix_paper_orders_order_id'), 'paper_orders', ['order_id'], unique=True)
    op.create_index(op.f('ix_paper_orders_paper_account_id'), 'paper_orders', ['paper_account_id'], unique=False)
    op.create_table('risk_events',
    sa.Column('rule_id', sa.String(length=36), nullable=True),
    sa.Column('signal_id', sa.String(length=36), nullable=True),
    sa.Column('order_id', sa.String(length=36), nullable=True),
    sa.Column('decision', sa.String(length=8), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.CheckConstraint("decision IN ('approve','veto','halt')", name=op.f('ck_risk_events_decision')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_risk_events_order_id_orders'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rule_id'], ['risk_rules.id'], name=op.f('fk_risk_events_rule_id_risk_rules'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], name=op.f('fk_risk_events_signal_id_signals'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_events'))
    )
    op.create_index(op.f('ix_risk_events_decision'), 'risk_events', ['decision'], unique=False)
    op.create_index(op.f('ix_risk_events_occurred_at'), 'risk_events', ['occurred_at'], unique=False)
    op.create_table('trade_tags',
    sa.Column('trade_id', sa.String(length=36), nullable=False),
    sa.Column('tag', sa.String(length=64), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_trade_tags_created_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], name=op.f('fk_trade_tags_trade_id_trades'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trade_tags')),
    sa.UniqueConstraint('trade_id', 'tag', name='trade_tag')
    )
    op.create_index(op.f('ix_trade_tags_tag'), 'trade_tags', ['tag'], unique=False)
    op.create_index(op.f('ix_trade_tags_trade_id'), 'trade_tags', ['trade_id'], unique=False)
    # ### end Alembic commands ###

    # Hand-written, and the order matters. The foreign key below points
    # users.role at roles.name; adding it against an empty roles table would
    # fail for every existing user. Seed first, then constrain. This is the
    # only change this migration makes to a pre-existing table, and it is
    # additive: no column is dropped, renamed or retyped, and no row changes.
    op.bulk_insert(
        sa.table(
            "roles",
            sa.column("name", sa.String),
            sa.column("rank", sa.Integer),
            sa.column("description", sa.String),
        ),
        [
            {"name": "user", "rank": 0,
             "description": "Read results: dashboards, journal, analytics"},
            {"name": "trader", "rank": 1,
             "description": "Brokers, strategies, bots, orders, AI models"},
            {"name": "admin", "rank": 2,
             "description": "Users, roles, platform controls"},
        ],
    )
    op.create_foreign_key(op.f('fk_users_role_roles'), 'users', 'roles', ['role'], ['name'])

    # webhook_events.signal_id -> signals.id closes a cycle (a signal also
    # points back at the event that produced it), so it has to be added after
    # both tables exist. Autogenerate does not emit use_alter constraints.
    op.create_foreign_key(
        "fk_webhook_signal", "webhook_events", "signals", ["signal_id"], ["id"],
        ondelete="SET NULL",
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Break the webhook_events <-> signals cycle before dropping either table.
    op.drop_constraint("fk_webhook_signal", "webhook_events", type_="foreignkey")
    op.drop_constraint(op.f('fk_users_role_roles'), 'users', type_='foreignkey')
    op.drop_index(op.f('ix_trade_tags_trade_id'), table_name='trade_tags')
    op.drop_index(op.f('ix_trade_tags_tag'), table_name='trade_tags')
    op.drop_table('trade_tags')
    op.drop_index(op.f('ix_risk_events_occurred_at'), table_name='risk_events')
    op.drop_index(op.f('ix_risk_events_decision'), table_name='risk_events')
    op.drop_table('risk_events')
    op.drop_index(op.f('ix_paper_orders_paper_account_id'), table_name='paper_orders')
    op.drop_index(op.f('ix_paper_orders_order_id'), table_name='paper_orders')
    op.drop_table('paper_orders')
    op.drop_index(op.f('ix_order_events_order_id'), table_name='order_events')
    op.drop_index(op.f('ix_order_events_occurred_at'), table_name='order_events')
    op.drop_table('order_events')
    op.drop_index(op.f('ix_journal_entries_user_id'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_trade_id'), table_name='journal_entries')
    op.drop_table('journal_entries')
    op.drop_index(op.f('ix_executions_order_id'), table_name='executions')
    op.drop_index(op.f('ix_executions_broker_deal_id'), table_name='executions')
    op.drop_table('executions')
    op.drop_index(op.f('ix_bot_events_occurred_at'), table_name='bot_events')
    op.drop_index(op.f('ix_bot_events_bot_run_id'), table_name='bot_events')
    op.drop_table('bot_events')
    op.drop_index(op.f('ix_trades_symbol_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_opened_at'), table_name='trades')
    op.drop_index(op.f('ix_trades_closed_at'), table_name='trades')
    op.drop_index(op.f('ix_trades_broker_position_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_position_events_position_id'), table_name='position_events')
    op.drop_index(op.f('ix_position_events_occurred_at'), table_name='position_events')
    op.drop_table('position_events')
    op.drop_index(op.f('ix_paper_positions_position_id'), table_name='paper_positions')
    op.drop_index(op.f('ix_paper_positions_paper_account_id'), table_name='paper_positions')
    op.drop_table('paper_positions')
    op.drop_index(op.f('ix_orders_symbol_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_intent_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_broker_order_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_model_predictions_signal_id'), table_name='model_predictions')
    op.drop_index(op.f('ix_model_predictions_predicted_at'), table_name='model_predictions')
    op.drop_index(op.f('ix_model_predictions_model_version_id'), table_name='model_predictions')
    op.drop_table('model_predictions')
    op.drop_index(op.f('ix_bot_runs_status'), table_name='bot_runs')
    op.drop_index(op.f('ix_bot_runs_bot_id'), table_name='bot_runs')
    op.drop_table('bot_runs')
    op.drop_index(op.f('ix_backtest_trades_entry_time'), table_name='backtest_trades')
    op.drop_index(op.f('ix_backtest_trades_backtest_id'), table_name='backtest_trades')
    op.drop_table('backtest_trades')
    op.drop_index(op.f('ix_training_runs_model_version_id'), table_name='training_runs')
    op.drop_table('training_runs')
    op.drop_index(op.f('ix_strategy_parameters_strategy_version_id'), table_name='strategy_parameters')
    op.drop_table('strategy_parameters')
    op.drop_index(op.f('ix_signals_symbol_id'), table_name='signals')
    op.drop_index(op.f('ix_signals_signal_time'), table_name='signals')
    op.drop_index(op.f('ix_signals_signal_key'), table_name='signals')
    op.drop_table('signals')
    op.drop_table('replay_sessions')
    op.drop_index(op.f('ix_positions_symbol_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_status'), table_name='positions')
    op.drop_index(op.f('ix_positions_broker_position_id'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_bots_user_id'), table_name='bots')
    op.drop_table('bots')
    op.drop_table('backtests')
    op.drop_index(op.f('ix_strategy_versions_strategy_id'), table_name='strategy_versions')
    op.drop_table('strategy_versions')
    op.drop_index(op.f('ix_portfolio_snapshots_taken_at'), table_name='portfolio_snapshots')
    op.drop_index(op.f('ix_portfolio_snapshots_paper_account_id'), table_name='portfolio_snapshots')
    op.drop_index(op.f('ix_portfolio_snapshots_broker_account_id'), table_name='portfolio_snapshots')
    op.drop_table('portfolio_snapshots')
    op.drop_index(op.f('ix_mt5_connections_broker_account_id'), table_name='mt5_connections')
    op.drop_table('mt5_connections')
    op.drop_index(op.f('ix_model_versions_model_id'), table_name='model_versions')
    op.drop_table('model_versions')
    op.drop_index(op.f('ix_strategies_key'), table_name='strategies')
    op.drop_table('strategies')
    op.drop_index(op.f('ix_paper_accounts_user_id'), table_name='paper_accounts')
    op.drop_table('paper_accounts')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_status'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_models_key'), table_name='models')
    op.drop_table('models')
    op.drop_index(op.f('ix_broker_accounts_user_id'), table_name='broker_accounts')
    op.drop_table('broker_accounts')
    op.drop_index(op.f('ix_audit_logs_occurred_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_symbol_mappings_symbol_id'), table_name='symbol_mappings')
    op.drop_table('symbol_mappings')
    op.drop_index(op.f('ix_webhook_events_idempotency_key'), table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_index(op.f('ix_system_events_occurred_at'), table_name='system_events')
    op.drop_index(op.f('ix_system_events_event_type'), table_name='system_events')
    op.drop_index(op.f('ix_system_events_correlation_id'), table_name='system_events')
    op.drop_index(op.f('ix_system_events_component'), table_name='system_events')
    op.drop_table('system_events')
    op.drop_index(op.f('ix_symbols_code'), table_name='symbols')
    op.drop_table('symbols')
    op.drop_table('roles')
    op.drop_table('risk_rules')
    # ### end Alembic commands ###
