"""symbol contract specs

Revision ID: 0003_symbol_specs
Revises: 0002_platform
Create Date: 2026-09-02 20:15:55.069386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0003_symbol_specs'
down_revision: Union[str, Sequence[str], None] = '0002_platform'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # NOT NULL on a table that may already hold rows needs a server default to
    # backfill with, and the default is then dropped so the column matches the
    # model exactly (the application always supplies the value). This database
    # happens to have no mapping rows yet; a deployment that does would fail
    # without it.
    op.add_column(
        'symbol_mappings',
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()),
    )
    op.alter_column('symbol_mappings', 'is_active', server_default=None)
    op.add_column('symbol_mappings', sa.Column('contract_size', sa.Numeric(precision=18, scale=8), nullable=True))
    op.add_column('symbol_mappings', sa.Column('tick_size', sa.Numeric(precision=18, scale=8), nullable=True))
    op.add_column('symbol_mappings', sa.Column('tick_value', sa.Numeric(precision=18, scale=4), nullable=True))
    op.add_column('symbol_mappings', sa.Column('minimum_volume', sa.Numeric(precision=18, scale=8), nullable=True))
    op.add_column('symbol_mappings', sa.Column('maximum_volume', sa.Numeric(precision=18, scale=8), nullable=True))
    op.add_column('symbol_mappings', sa.Column('volume_step', sa.Numeric(precision=18, scale=8), nullable=True))
    op.add_column('symbol_mappings', sa.Column('price_precision', sa.Integer(), nullable=True))
    op.add_column('symbol_mappings', sa.Column('volume_precision', sa.Integer(), nullable=True))
    op.add_column('symbol_mappings', sa.Column('trading_hours', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.add_column('symbol_mappings', sa.Column('spec_source', sa.String(length=16), nullable=True))
    op.add_column('symbol_mappings', sa.Column('spec_updated_at', sa.DateTime(), nullable=True))
    op.create_check_constraint(op.f('ck_symbol_mappings_spec_source'), 'symbol_mappings', "spec_source IS NULL OR spec_source IN ('mt5_terminal','manual','provider_api')")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_symbol_mappings_spec_source'), 'symbol_mappings', type_='check')
    op.drop_column('symbol_mappings', 'spec_updated_at')
    op.drop_column('symbol_mappings', 'spec_source')
    op.drop_column('symbol_mappings', 'trading_hours')
    op.drop_column('symbol_mappings', 'volume_precision')
    op.drop_column('symbol_mappings', 'price_precision')
    op.drop_column('symbol_mappings', 'volume_step')
    op.drop_column('symbol_mappings', 'maximum_volume')
    op.drop_column('symbol_mappings', 'minimum_volume')
    op.drop_column('symbol_mappings', 'tick_value')
    op.drop_column('symbol_mappings', 'tick_size')
    op.drop_column('symbol_mappings', 'contract_size')
    op.drop_column('symbol_mappings', 'is_active')
    # ### end Alembic commands ###
