"""market_bars: a provenance-carrying bar cache (L08).

Purely additive. One new table, no column altered, no row rewritten, so the
252 trades, 269 orders and 9 symbols already stored are untouched -- there is
no destructive step here and therefore no guard needed to refuse one.

The table exists for two reasons that a live provider cannot give:

  * **Idempotent ingestion.** The unique key (provider, provider_symbol,
    timeframe, bar_time) makes a replayed fetch a no-op instead of a duplicate
    candle. A provider retry or a reconnect replays bars as a matter of course.
  * **Deterministic replay.** L15 needs a series that does not change under it
    between runs.

`provider` is part of the key on purpose: two providers' "EURUSD H1" sit side
by side and are never averaged. They are different measurements of different
books, and this project has a measured record of what pooling unlike
quantities does to a result.

The OHLC check constraint is duplicated from `app.marketdata.validation`
deliberately. A bar that reaches this table by any other path is still a bar,
and the database is the last place the four relationships can be enforced.

Revision ID: 0006_market_bars
Revises: 0005_auth_hardening
Create Date: 2026-09-03

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0006_market_bars'
down_revision: Union[str, Sequence[str], None] = '0005_auth_hardening'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_bars',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('provider_symbol', sa.String(length=64), nullable=False),
    sa.Column('symbol_id', sa.String(length=36), nullable=True),
    sa.Column('timeframe', sa.String(length=4), nullable=False),
    sa.Column('bar_time', sa.DateTime(), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('high', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('low', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('close', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('volume', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('spread', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('spread_availability', sa.String(length=16), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("provider IN ('mt5','tradingview','ccxt','yfinance','simulator')", name=op.f('ck_market_bars_provider')),
    sa.CheckConstraint("timeframe IN ('M1','M5','M15','M30','H1','H4','D1','W1')", name=op.f('ck_market_bars_timeframe')),
    sa.CheckConstraint('high >= low AND high >= open AND high >= close AND low <= open AND low <= close', name=op.f('ck_market_bars_ohlc_consistent')),
    sa.CheckConstraint('open > 0 AND high > 0 AND low > 0 AND close > 0', name=op.f('ck_market_bars_prices_positive')),
    sa.CheckConstraint('spread IS NULL OR spread >= 0', name=op.f('ck_market_bars_spread_not_negative')),
    sa.CheckConstraint('volume IS NULL OR volume >= 0', name=op.f('ck_market_bars_volume_not_negative')),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], name=op.f('fk_market_bars_symbol_id_symbols'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_bars')),
    sa.UniqueConstraint('provider', 'provider_symbol', 'timeframe', 'bar_time', name='market_bar_identity')
    )
    op.create_index('ix_market_bars_series', 'market_bars', ['provider', 'provider_symbol', 'timeframe', 'bar_time'], unique=False)
    op.create_index(op.f('ix_market_bars_symbol_id'), 'market_bars', ['symbol_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Drops the cache. No other table references it, and nothing is lost that
    a provider cannot serve again."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_market_bars_symbol_id'), table_name='market_bars')
    op.drop_index('ix_market_bars_series', table_name='market_bars')
    op.drop_table('market_bars')
    # ### end Alembic commands ###
